spring:
  application:
    name: XCampo
  datasource:
    url: jdbc:mariadb://localhost:3307/XCampo
    username: root
    password: 1234567890
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
      open-in-view: false


server:
  port: 8080
  servlet:
    context-path: /XCampo/api/v1

servlet:
  multipart:
    enabled: true
    max-file-size : 10MB
    max-request-size: 10MB




