spring:
  application:
    name: XCampo
  datasource:
    url: jdbc:mariadb://localhost:3307/XCampo
    username: root
    password: 1234567890
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
      open-in-view: false

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /XCampo/api/v1

servlet:
  multipart:
    enabled: true
    max-file-size : 10MB
    max-request-size: 10MB



jwt:
    secret : miClaveSecreta
    secretKey : LKFLGJLJDFHJKDHFJKGJKSADFKJADSHFJKGKDJSHGDFKJGH
    expiration : 900000 # 15 minutos en milisegundos para el Access Token
    refreshExpiration : 1296000000 # 7 días en milisegundos para el Refresh Token


logging:
  level:
    org:
      springframework:
        boot:
          logging: DEBUG

